# Generated by Django 6.0.3 on 2026-05-12 18:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_category_image_url_remove_product_image_urls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
